apiVersion: v1
kind: Service
metadata:
  name: ltr-ejb-service
  namespace: ltr-ejb
  labels:
    app: ltr-ejb
    component: ejb-module
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: ltr-ejb
